### PR TITLE
Test-dependencies with composer

### PR DESCRIPTION
**Pull request by mheiniger**
Update Phing to local installed packages with "Composer" instead of globally installed pear packages.
Makes the building process more operating-system independent.

### CODE REVIEW

**Comment by bcordis** [comment]
Not attached to any milestone as this is independent of the component working.

**Comment by mheiniger** [comment]
Yes.. is something like "infrastructure work" for developers to have an easier ramp-up

**Comment by bcordis** [comment]
Put ready label when you have a test version.

**Comment by mheiniger** [comment]
I think its now ready for you to review. All phing tasks of `phing build` work now, including phpunit.

The added files in the folder tests/unit/core/ are taken from the Joomla 3.3.6, and also the phpcs ruleset is completed from there.

**Comment by bcordis** [comment]
@genu Can you also take a look at this. From what i can see it look really good. I would like to merge this by are next meeting.

**Pull request merged**
