### PR TITLE
9.0.1

### PR DESCRIPTION
**Pull request by bcordis**
Small fixes.

### CODE REVIEW

**Comment by bcordis** [comment]
I have used phpstorm to inspect all the code and have found a few errors.

I corrected all i could and opened a few Issues to for @tomfuller2 to look into.

**Comment by bcordis** [comment]
Ok now we have fixed the errors.  I still need to add some deletion to the next file set.

**Comment by bcordis** [comment]
Moving to 9.0.1 do to update system. Will be releasing stable version once merged. Have a few media defaults to work on but close to being finished.

**Comment by bcordis** [comment]
@tomfuller2 Look at the new system that now pulls over the defaults from Servers on Creation of new media. Work also if changing servers.

**Comment by tomfuller2** [comment]
Looks good!

**Comment by bcordis** [comment]
Delayed till Friday 15 2016

**Comment by bcordis** [comment]
Close now as we have made it now progress on the stepper and how it will work with large data basses. 

I have a few more bugs to work out then we are going into testing again.

**Comment by bcordis** [comment]
@tomfuller2 This is working now. I have a function that will need to be removed on release but allows you to update you db and run the install state every time.

I works right. Please debug.

**Pull request merged**
