### PR TITLE
Newinstaller

### PR DESCRIPTION
**Pull request by bcordis**
Move to new installer. This will fix the problem with server timeout and staging of the installation.

This will step through each install and then into migration as needed.

### CODE REVIEW

**Comment by tomfuller2** [comment]
Did you guys get it working? Migrating and installing fresh?

I might get a chance to test before I head out of state Wednesday but am
pretty packed.

**Comment by bcordis** [comment]
It's not totally ready as I'm still working though bugs.  Migration is not
tested and have not don a cleen install only tested by removing the db and
it reinstalled the db properly.

Hope to do more this weekend.

On Friday, January 1, 2016, Tom Fuller <notifications@github.com> wrote:

> Did you guys get it working? Migrating and installing fresh?
>
> I might get a chance to test before I head out of state Wednesday but am
> pretty packed.
>
> On Friday, January 1, 2016, Brent Cordis <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Closed #618
> > <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/pull/618>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/pull/618#event-503833284
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/pull/618#issuecomment-168351140>
> .
>


-- 
Sent from Gmail Mobile

**Comment by tomfuller2** [comment]
Okay. Just thought it was done since you closed the issue.

**Comment by bcordis** [comment]
Had to rebuild the code so the pull request closed have to open a new one.

**Pull request closed without merging**
