### PR TITLE
[work-in-progress] Feature: added composer instead of pear

### PR DESCRIPTION
**Pull request by mheiniger**
As the future goes away from pear and in direction of composer (and is wasnt able to install the correct versions with pear on my ubuntu machine), i started to use composer for for development.

The big plus: its less depending on whats installed on a machine, because it installs everything inside the "vendor" folder of the project.

Maybe it can be a first step in that direction.
On development branch i tried it too, but at the current state i can't get it running, maybe it needs different packages.

### CODE REVIEW

**Comment by bcordis** [comment]
Until you can get a stable version of composer working I'll keep the pull open.

We right now use phing to build the packages and move test data around.

**Comment by bcordis** [comment]
When you are ready for us to review the pull request pleas add Labile 1-ready

**Comment by bcordis** [comment]
@mheiniger do you still want to do this pull or are you good with phing now? we have been using it for a quite a will.

Let me know what you are thinking of?

**Comment by mheiniger** [comment]
Its not about removing phing, its about removing the need of globally installing pear-packages. Phing will then be installed with composer into the vendors directory.

**Comment by bcordis** [comment]
Just let me know when you have a tested system. Then I'll test before putting it into dev.

**Comment by mheiniger** [comment]
Yes i will.. the problem is, that the phpunit tests on your development branch fail, so before that is fixed i never know if the errors are because of my changes or because of the problems of the tests of the development branch.

**Comment by bcordis** [comment]
We never worked up phpunit yet so if you know it well you can start working it up. Have not had time. Let me know if you need help there.

**Comment by mheiniger** [comment]
This pull-request is on the wrong branch anyways. I will close it and open one for the development branch.

**Pull request closed without merging**
